# mysql
MYSQL_HOST: 127.0.0.1
MYSQL_PASSWORD: '123456'
MYSQL_USER: root
MYSQL_DB: dev
MYSQL_PORT: 3306


# redis > 2
REDIS_HOST: 127.0.0.1
REDIS_PORT: 16379
REDIS_DB: 2


# rabbitmq
RABBITMQ_HOST: 127.0.0.1
RABBITMQ_USER: queue_send_user
RABBITMQ_PASSWORD: '123456'
RABBITMQ_PORT: 5672
RABBITMQ_VHOST: queue_send_vhost
RABBITMQ_SIZE: 100
RABBITMQ_PREFETCH_COUNT: 1
RABBITMQ_QUEUE: async_send_queue